#!/bin/bash
# Execute this script, or run individual lines you want. Don't symlink this to ~/.gitconfig.
set -x

# NeoBundle makes vim bork out when run as vi (which is git default)
#git config --global core.editor $(which vim)

# Find the branching point http://stackoverflow.com/a/4991675
git config --global alias.oldest-ancestor "!bash -c '"$'git log -1 "$(diff --old-line-format= --new-line-format= <(git rev-list --first-parent "${1:-master}") <(git rev-list --first-parent "${2:-HEAD}") | head -1)"'"' -"

# Sort branch by date (run git bs -a to include remote branches and tags)
git config --global alias.bs $'!f() { [[ "$1" = "-a" ]] && refs="--" || refs="refs/heads/"; git for-each-ref --format="%(committerdate:raw)%(taggerdate:raw)%(committerdate:relative)%(taggerdate:relative)\t%(refname:short) %(color:red)%(subject) %(color:blue)%(authorname)" "$refs" | sort -k1,1 | cut -c17-; }; f'

# Short log
git config --global alias.l '!'"git --no-pager log --graph --format='%C(auto)%h%C(reset) - %cr %d %C(red)%s%C(reset) %C(blue)%cn%C(reset)' -5"

# Full log graph
git config --global alias.lg "log --all --graph --format='%C(auto)%h%C(reset) - %cr %d %C(red)%s%C(reset) %C(blue)%cn%C(reset)'"

# Short status
git config --global alias.s "status -s"

# More readable diff
git config --global alias.d "diff --patience"

# Diff staged
git config --global alias.ds "diff --patience --staged"

# Show branches
git config --global alias.b "branch"

# Update both branches and tags
git config --global alias.f "!git fetch --all --prune 2>&1 | sed 's/^/branches: /'; git fetch --all --prune --tags 2>&1 | sed 's/^/tags: /'"

# Add color to git output
git config --global color.ui auto

# Push only the current branch
git config --global push.default current

# Show the original code in merge conflicts
git config --global merge.conflictstyle diff3

# Show other changes when doing git pull --rebase
git config --global rebase.stat true

# Enable git rerere
git config --global rerere.enabled true

# Fetch pull requests too
#git config --global --add remote.origin.fetch "+refs/pull/*/head:refs/remotes/origin/pr/*"

# Show the patch by default with git stash show
git config --global stash.showPatch true

# Automatically stash and unstash before and after a rebase
git config --global rebase.autoStash true

# Show ref names in git log
git config --global log.decorate full

# Show all untracked files in git status, not just root directories
git config --global status.showUntrackedFiles all

# Verify transferred objects in exchange for slower transfer
# If you have errors cloning or fetching, use --config transfer.fsckObjects=false
git config --global transfer.fsckObjects true

# easy git instaweb
git config --global instaweb.local true
git config --global instaweb.httpd webrick

# Fix git rebases on mac
# https://www.git-tower.com/blog/make-git-rebase-safe-on-osx/
if [[ "$(uname)" = "Darwin" ]]; then
    git config --global core.trustctime false
fi

# Update sandbox branch
# Old, but maybe a useful reference for shell functions in git aliases
# * origin/master is merged into your branch
# * your branch is pushed to the sandbox
#git config --global alias.update-sandbox $'!f() ( set -euo pipefail; if [[ "$#" -ne 1 ]]; then echo "Usage: update-sandbox <sandbox-name>"; echo "Example: update-sandbox pear"; exit 1; fi; set -x; git fetch; git merge origin/master; git push origin "HEAD:$1" || { set +x; echo "Force push required. Press any key to continue or ctrl+c to abort: "; read; set -x; git push --force origin "HEAD:$1"; } ); f'

